---

- name: Wait some minutes for report
  pause:
    minutes: 3

- name: Facts public EC2 instance
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Role": master
      instance-state-name: running
  register: public_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Role": worker
      instance-state-name: running
  register: private_ec2_facts

- name: Clean content inventories file
  shell: echo " " > "{{ path_hosts_group }}"/inventories/staging/hosts

- name: Write public group to inventories file
  lineinfile:
    dest: "{{ path_hosts_group }}/inventories/staging/hosts"
    insertafter: EOF
    line: "[public]"

- name: Write public host to inventories file
  lineinfile:
    dest: "{{ path_hosts_group }}/inventories/staging/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
  with_together: 
        - "{{ public_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ public_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: Write private group to inventories file
  lineinfile:
    dest: "{{ path_hosts_group }}/inventories/staging/hosts"
    insertafter: EOF
    line: "[private]"


- name: Write private host  to file
  lineinfile:
    dest: "{{ path_hosts_group }}/inventories/staging/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
  with_together: 
        - "{{ private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

